### ISSUE TITLE
实现居中

### ISSUE THREAD

**Issue by tangzhenming** [tangzhenming/answer-the-question-FE#25]
## 不定宽高的元素水平垂直居中

1. 使用弹性盒子 `flex`（推荐👍👍）

   ```css
   .parent {
     display: flex;
     justify-content: center;
     align-items: center;
   }
   ```

2. 结合绝对定位，使用 css3 的 `transform` 属性（推荐👍）

   ```css
   /**
    * 50%并不是居中的，因为它是以元素的上border为标准移动50%的
    * 所以我们需要向上移动元素自身高度一半儿的距离
    */
   .parent {
     position: relative;
     .child {
       position: absolute;
       top: 50%;
       left: 50%;
       transform: translate(-50%, -50%);
     }
   }
   ```

3. 使用 `table` 布局（不推荐👎）

   ```css
   .parent {
     display: table-cell;
     text-align: center;
     vertical-align: middle;
     .child {
       display: inline-block;
       vertical-align: middle;
     }
   }
   ```

## 文本垂直居中使用 line-height

```css
.parent {
  height: 100px;
  line-height: 100px;
}
```

## 图片垂直居中使用 line-height & vertical-align

```css
.parent {
  height: 100px;
  line-height: 100px;
  img {
    width: 50px;
    height: 50px;
    vertical-align: middle;
  }
}
```

## 使用 CSS Grid 垂直居中

```css
.parent {
  display: grid;
  .child-one {}
  .child-two-center {}
  .child-three {}
}
```
