### ISSUE TITLE
清除浮动

### ISSUE THREAD

**Issue by tangzhenming** [tangzhenming/answer-the-question-FE#39]
浮动元素会脱离文档流，导致其父元素高度坍塌。

避免产生浮动元素的父元素产生高度坍塌的方案，就是清除浮动。

清除浮动有两种方式：

1. 利用 clear 属性
2. 利用 BFC

```html
<style>
  .box-wrapper {
    border: 5px solid red;
  }
  .box-wrapper .box {
    float: left; 
    width: 100px; 
    height: 100px; 
    margin: 20px; 
    background-color: green;
  }
</style>

<div class="box-wrapper">
  <div class="box"></div>
  <div class="box"></div>
  <div class="box"></div>
</div>
```

## 1. clear 属性

clear 属性不允许设置该属性的元素周围存在浮动元素。

所以我们通过在其他元素上设置 clear 属性实现高度的撑开：

```html
<div class="box-wrapper">
    <div class="box"></div>
    <div class="box"></div>
    <div class="box"></div>
    <div style="clear:both;"></div>
</div>
```

最佳实践是使用父元素的伪元素来设置 clear 属性：

```css
// 全浏览器通用的clearfix方案【推荐】
// 引入了zoom以支持IE6/7
// 同时加入:before以解决现代浏览器上边距折叠的问题
.clearfix:before,
.clearfix:after {
    display: table;
    content: " ";
}
.clearfix:after {
    clear: both;
}
.clearfix{
    *zoom: 1;
}
```

## 2. BFC

利用 BFC 可以包含浮动的特性：

```css
// example
.box-wrapper{
  overflow: auto;
}
```
